version: 2.1

orbs:
  python: circleci/python@0.2.1
jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - store_test_results:
            path: test-results
      - run:
          command: chmod u+rwx ./API_Tests/manage.py
      - store_test_results:
          path: /tmp/test.xml

workflows:
  main:
    jobs:
      - build-and-test