version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: TestBaseAPI
          command: python -m pytest ./API_Tests/test_Base_API.py --junitxml=test-reports/TestBaseAPI.xml --html=test-reports/TestBaseAPI.html --self-contained-html
      - run:
          name: TestInternetConnection
          command: python -m pytest ./API_Tests/test_InternetConnection.py --junitxml=test-reports/TestInternetConnection.xml --html=test-reports/TestInternetConnection.html --self-contained-html
      - run:
          name: TestOfflineData
          command: python -m pytest ./API_Tests/test_offline_Data.py --junitxml=test-reports/TestOfflineData.xml --html=test-reports/TestOfflineData.html --self-contained-html
      - run:
          name: IntegrationTest
          command: python -m pytest ./API_Tests/Integration_test.py --junitxml=test-reports/Integration.xml --html=test-reports/Integration.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  main:
    jobs:
      - build-and-test