version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
        - python/load-cache
        - python/install-deps
        - python/save-cache
      - run:
          name: Run unit Tests
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  main:
    jobs:
      - build-and-test